# -*- coding: utf-8 -*-
"""DPOtrainer3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SC6rp3zL62BAruW4ePZF8VLjwhPA8A5G
"""

!pip install transformers peft trl datasets accelerate bitsandbytes

pip install dataset

import os
import json
import re
import time
import torch
import sys  # ✅ Import sys to handle unwanted arguments
from dataclasses import dataclass, field
from typing import Optional

from datasets import Dataset, load_dataset
from peft import LoraConfig, get_peft_model
from transformers import AutoModelForCausalLM, AutoTokenizer, HfArgumentParser, BitsAndBytesConfig, DataCollatorWithPadding
from trl import DPOConfig, DPOTrainer

# ✅ Mount Google Drive (if using Drive for storage)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# 🔹 Define Base Directories
shared_drive_base = "/content/drive/MyDrive/THESIS/DPO_Trainer"
datasets_dir = f"{shared_drive_base}/Datasets"
model_dir = f"{shared_drive_base}/Models"

# 🔹 Define Paths
JSON_DATA_PATH = f"{datasets_dir}/CompiledET.json"
MULTI_LANG_MODEL = f"{model_dir}/PestAway_Final_QWEN_SFT_Epoch4"
new_model = f"{model_dir}/PestAway_Final_QWEN_DPO_E1"

# 🔹 Load tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(MULTI_LANG_MODEL)
model = AutoModelForCausalLM.from_pretrained(
    MULTI_LANG_MODEL,
    torch_dtype=torch.float16,  # Adjust dtype based on Colab GPU
    low_cpu_mem_usage=True
)
model.config.use_cache = False

@dataclass
class ScriptArguments:
    beta: Optional[float] = field(default=0.1)
    model_name_or_path: Optional[str] = field(default=MULTI_LANG_MODEL)
    learning_rate: Optional[float] = field(default=5e-6)
    per_device_train_batch_size: Optional[int] = field(default=4)  # Reduce batch size for Colab
    gradient_accumulation_steps: Optional[int] = field(default=4)  # Adjust for Colab VRAM
    warmup_steps: Optional[int] = field(default=500)
    max_grad_norm: Optional[float] = field(default=1.0)
    lora_alpha: Optional[float] = field(default=16)
    lora_dropout: Optional[float] = field(default=0.1)
    lora_r: Optional[int] = field(default=64)
    max_prompt_length: Optional[int] = field(default=64)
    max_length: Optional[int] = field(default=512)
    num_train_epochs: Optional[int] = field(default=2)
    output_dir: Optional[str] = field(default="./dpo_results")

# 🔹 Load and process dataset
def load_and_process_data(data_path: str) -> Dataset:
    dataset = load_dataset('json', data_files=data_path, split='train')

    def process_data(sample):
        if "rejected" not in sample:
            sample["rejected"] = "No response provided"
        return {"prompt": sample["prompt"], "chosen": sample["chosen"], "rejected": sample["rejected"]}

    return dataset.map(process_data, remove_columns=dataset.column_names)

# 🔹 Model evaluation function
def evaluate_model_with_prompt(model, tokenizer, prompt: str):
    model.eval()
    inputs = tokenizer(prompt, return_tensors="pt", max_length=64, truncation=True).input_ids.to(model.device)

    with torch.no_grad():
        output = model.generate(
            inputs,
            max_new_tokens=256,
            pad_token_id=tokenizer.pad_token_id,
            no_repeat_ngram_size=3,
            top_k=50,
            top_p=0.95,
            temperature=0.7,
            eos_token_id=tokenizer.eos_token_id
        )

    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
    generated_answer = generated_text[len(prompt):].strip()
    sentences = re.split(r'[.?!]', generated_answer)
    meaningful_answer = sentences[0].strip() if sentences else generated_answer
    print(f"Question: {prompt}\nAnswer: {meaningful_answer}")

# ✅ Run the script
if __name__ == "__main__":
    # ✅ Fix for Colab's extra arguments
    sys.argv = [sys.argv[0]]  # Remove unwanted Jupyter-related arguments

    parser = HfArgumentParser(ScriptArguments)
    script_args = parser.parse_args_into_dataclasses()[0]  # ✅ Fixed argument parsing

    bnb_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16)

    model = AutoModelForCausalLM.from_pretrained(
        script_args.model_name_or_path,
        quantization_config=bnb_config,
        low_cpu_mem_usage=True,
        torch_dtype=torch.float16,  # Adjust for Colab's GPU
    )
    model.config.use_cache = False
    tokenizer.pad_token = tokenizer.eos_token

    # ✅ Load dataset
    train_dataset = load_and_process_data(JSON_DATA_PATH)
    train_dataset = train_dataset.filter(lambda x: len(x["prompt"]) + len(x["chosen"]) <= script_args.max_length)

    # ✅ LoRA Config
    peft_config = LoraConfig(
        r=script_args.lora_r,
        lora_alpha=script_args.lora_alpha,
        lora_dropout=script_args.lora_dropout,
        target_modules=["q_proj", "v_proj", "k_proj", "out_proj", "fc_in", "fc_out", "wte"],
        bias="none",
        task_type="CAUSAL_LM",
    )

    model = get_peft_model(model, peft_config)

    # ✅ Training arguments
    training_args = DPOConfig(
        beta=script_args.beta,
        max_prompt_length=script_args.max_prompt_length,
        max_length=script_args.max_length,
        output_dir=script_args.output_dir,
        per_device_train_batch_size=script_args.per_device_train_batch_size,
        gradient_accumulation_steps=script_args.gradient_accumulation_steps,
        learning_rate=script_args.learning_rate,
        warmup_steps=script_args.warmup_steps,
        max_grad_norm=script_args.max_grad_norm,
        num_train_epochs=script_args.num_train_epochs
    )

    # ✅ Initialize trainer
    dpo_trainer = DPOTrainer(
        model=model,
        ref_model=None,
        args=training_args,
        train_dataset=train_dataset,
        processing_class=AutoTokenizer.from_pretrained(MULTI_LANG_MODEL)
    )

    # ✅ Train the model
    dpo_trainer.train()

    # ✅ Merge LoRA into base model
    merged_model = model.merge_and_unload()

    # ✅ Save final model
    merged_model.save_pretrained(new_model)
    tokenizer.save_pretrained(new_model)

    print(f"✅ Training complete. Merged model saved to: {new_model}")