# -*- coding: utf-8 -*-
"""SFT Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LpigExZak0kKetdYEPlpnkSXNCt31hhi
"""

import json
import re
from pprint import pprint
import pandas as pd
import torch
from datasets import load_dataset
from huggingface_hub import notebook_login
from peft import LoraConfig, PeftModel
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    pipeline,
    logging,
)
from trl import SFTTrainer
import time
import os

# Set environment variables to suppress warnings
os.environ['TRANSFORMERS_NO_ADVISORY_WARNINGS'] = 'true'
# NOTE: Do NOT hardcode tokens. Set HF_TOKEN in your environment or .env (not committed).
hf_token = os.getenv("HF_TOKEN")
if hf_token:
    os.environ["HF_TOKEN"] = hf_token
else:
    # Optional: uncomment if you want an interactive login in notebooks/Colab
    # from huggingface_hub import login
    # login()

# Load the training and test datasets
train_parquet_file = os.getenv("TRAIN_PARQUET", "./data/train.parquet")  # set env var or use relative path
test_parquet_file = os.getenv("TEST_PARQUET", "./data/test.parquet")    # set env var or use relative path
dataset = load_dataset("parquet", data_files={'train': train_parquet_file, 'test': test_parquet_file})

# Model configuration
model_name = "dost-asti/gpt2-tl-cased"
new_model = "PestAway_Final_MT1"
start_time = time.time()

# LoRA configurations
lora_r = 64
lora_alpha = 16
lora_dropout = 0.1

# TrainingArguments configurations
output_dir = "./results"
num_train_epochs = 1
fp16 = True
bf16 = False
per_device_train_batch_size = 4
per_device_eval_batch_size = 4
gradient_accumulation_steps = 1
gradient_checkpointing = True
max_grad_norm = 1
learning_rate = 1e-5
weight_decay = 0.001
optim = "adamw_hf"
lr_scheduler_type = "cosine"
max_steps = -1
warmup_ratio = 0.03
group_by_length = True
save_steps = 2000
logging_steps = 25
eval_strategy = 'epoch'

# Load the base GPT model with device configuration
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
)

# Disable cache for training
base_model.config.use_cache = False

# Load the GPT-2 tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# LoRA configuration specific to mGPT
peft_config = LoraConfig(
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    r=lora_r,
    target_modules=[
        "attn.c_attn",
        "mlp.c_fc",
        "mlp.c_proj",
    ],
    bias="none",
    task_type="CAUSAL_LM",
)

# Training configuration
training_arguments = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=num_train_epochs,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    save_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    weight_decay=weight_decay,
    fp16=fp16,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=group_by_length,
    lr_scheduler_type=lr_scheduler_type,
    report_to="wandb",
    eval_strategy=eval_strategy,
)

# SFTTrainer initialization
trainer = SFTTrainer(
    model=base_model,
    train_dataset=dataset['train'],
    eval_dataset=dataset['test'],
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length=None,
    tokenizer=tokenizer,
    args=training_arguments,
    packing=False,
)

# Train the model
trainer.train()

# Save the trained model
trainer.model.save_pretrained(new_model)

# Merge the base model and fine-tuned model
merged_model = PeftModel.from_pretrained(base_model, new_model)
merged_model = merged_model.merge_and_unload()

# Save the merged model
merged_model.save_pretrained("PestAway_Final", safe_serialization=True)
tokenizer.save_pretrained("PestAway_Final")

# Evaluate the model with a prompt
eval_prompt = """How does basil extract help manage aphid infestations in corn?"""
model_input = tokenizer(eval_prompt, return_tensors="pt").to("cuda")

merged_model.eval()
with torch.no_grad():
    output = merged_model.generate(
        **model_input,
        max_new_tokens=256,
        pad_token_id=tokenizer.pad_token_id,
        no_repeat_ngram_size=3,
        top_k=50,
        top_p=0.95,
        temperature=0.7,
        eos_token_id=tokenizer.eos_token_id
    )

    # Decode the output to text
    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)

    # Remove the input prompt from the generated response
    generated_answer = generated_text[len(eval_prompt):].strip()
    sentences = re.split(r'[.?!]', generated_answer)
    meaningful_answer = sentences[0].strip()

    # Print the question and answer
    print(f"Question: {eval_prompt}\nAnswer: {meaningful_answer}")

# Record the end time and print the training duration
end_time = time.time()
training_time = end_time - start_time
print(f"Training took {training_time} seconds")
